package com.fauna.mapping;

/**
 * Enum representing the different types of fields that can be used in Fauna document field mappings.
 * Each field type specifies a distinct role or characteristic of a field in the mapping process.
 */
public enum FieldType {

    /**
     * Represents a client-generated document ID.
     * Typically used when the ID is provided by the client and not generated by Fauna.
     */
    ClientGeneratedId,

    /**
     * Represents a Fauna-generated document ID.
     * Typically used for document IDs auto-generated by Fauna.
     */
    ServerGeneratedId,

    /**
     * Represents the document's `coll` (collection) metadata field.
     * Used to denote the collection to which the document belongs.
     */
    Coll,

    /**
     * Represents the document's `ts` (timestamp) metadata field.
     * Used to track the last write to the document.
     */
    Ts,

    /**
     * Represents a user-defined document field.
     */
    Field,
}
