package com.fauna.mapping;

/**
 * Enum representing the different types of fields that can be used in Fauna mappings.
 * Each field type specifies a distinct role or characteristic of a field in the mapping process.
 */
public enum FieldType {

    /**
     * Represents a client-generated identifier field.
     * Typically used when the ID is provided by the client and not generated by the server.
     */
    ClientGeneratedId,

    /**
     * Represents a server-generated identifier field.
     * Typically used for IDs generated by the Fauna server automatically.
     */
    ServerGeneratedId,

    /**
     * Represents a collection (coll) field, used to denote the collection to which a document belongs.
     */
    Coll,

    /**
     * Represents a timestamp (ts) field, used to track the timestamp of a document.
     */
    Ts,

    /**
     * Represents a field for user-defined data.
     */
    Field,
}
