---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook))

  - name: repo.git
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/fauna-jvm.git
      branch: main
      private_key: ((github-ssh-key))

  - name: fauna-jvm-repository
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/fauna-jvm.git
      branch: release
      private_key: ((github-ssh-key))

  - name: fauna-jvm-repository-docs
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/fauna-jvm.git
      branch: gh-pages
      private_key: ((github-ssh-key))
  - name: testtools-repo
    type: git
    icon: github
    source:
      uri: git@github.com/fauna/testtools.git
      branch: main
      private_key: ((github-ssh-key))
  - name: testtools-image
    type: registry-image
    icon: docker
    source:
      repository: devex-dx-drivers-platform-tests
      aws_access_key_id: ((prod-images-aws-access-key-id))
      aws_secret_access_key: ((prod-images-aws-secret-key))
      aws_region: us-east-2

  - name: perf-notify
    type: slack-notification
    source:
      # webhook for #notify-driver-perf channel
      url: ((driver-perf-slack-url))

  - name: dev-tests-trigger
    type: time
    source:
      interval: 6h

jobs:
  - name: set-self
    serial: true
    plan:
      - get: repo.git
        trigger: true
      - set_pipeline: self
        file: repo.git/concourse/pipeline.yml

  - name: tests-dev
    serial: true
    public: false
    plan:
      - get: dev-tests-trigger
        trigger: true

      - get: repo.git
      - get: testtools-repo
      - get: testtools-image

      - in_parallel:
          fail_fast: false
          steps:
            - task: run-perf
              file: repo.git/concourse/tasks/perf.yml
              params:
                FAUNA_ENDPOINT: https://db.fauna-dev.com
                FAUNA_SECRET: ((dev-driver-perf-test-key))
                FAUNA_ENVIRONMENT: dev
                CONCOURSE_URL: http://concourse.faunadb.net/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
              on_success:
                put: perf-notify
                params:
                  text_file: slack-message/perf-stats
            - task: aws-lambda-tests
              image: testtools-image
              file: testtools-repo/fauna-driver-platform-tests/concourse/tasks/java-aws-lambda-tests.yml
              params:
                GIT_COMMIT: ((.:git-commit))
                FAUNA_SECRET: ((drivers-platform-tests/fauna-secret))
                AWS_LAMBDA_ROLE_ARN: ((drivers-platform-tests/aws-lambda-role-arn))
                AWS_ACCESS_KEY_ID: ((drivers-platform-tests/aws-access-key-id))
                AWS_SECRET_ACCESS_KEY: ((drivers-platform-tests/aws-secret-key))
  - name: release
    serial: true
    public: false
    plan:
      - get: fauna-jvm-repository
        trigger: true
      - get: fauna-jvm-repository-docs

      # - in_parallel:
      #   - task: integration-tests-oracle-jdk11
      #     file: fauna-jvm-repository/concourse/tasks/integration-tests-oracle-jdk11.yml
      #     privileged: true
      #     vars:
      #       aws_access_key_id: ((concourse_aws_access_key_id))
      #       aws_secret_access_key: ((concourse_aws_access_key_secret))
      #     params:
      #       FAUNA_ROOT_KEY: ((fauna.secret))
      #       FAUNA_DOMAIN: ((fauna.domain))
      #       FAUNA_SCHEME: ((fauna.scheme))
      #       FAUNA_PORT: ((fauna.port))
      #       AWS_ACCESS_KEY_ID: ((concourse_aws_access_key_id))
      #       AWS_SECRET_ACCESS_KEY: ((concourse_aws_access_key_secret))
      #       AWS_DEFAULT_REGION: us-east-2

      #   - task: integration-tests-openjdk11
      #     file: fauna-jvm-repository/concourse/tasks/integration-tests-jdk11.yml
      #     privileged: true
      #     params:
      #       FAUNA_ROOT_KEY: ((fauna.secret))
      #       FAUNA_DOMAIN: ((fauna.domain))
      #       FAUNA_SCHEME: ((fauna.scheme))
      #       FAUNA_PORT: ((fauna.port))

      - task: publish
        file: fauna-jvm-repository/concourse/tasks/publish.yml
        params:
          MAVENCENTRAL_USER: ((mavencentral-user))
          MAVENCENTRAL_PASSWORD: ((mavencentral-password))
          SIGNING_KEYID: ((gpg-keyid))
          SIGNING_KEY: ((gpg-private-key))
          SIGNING_KEYPASSWORD: ((gpg-passphrase))
          GIT_PRIVATE_KEY: ((github-ssh-key))
        on_success:
          put: notify
          params:
            text_file: slack-message/publish

      - put: fauna-jvm-repository
        params:
          repository: fauna-jvm-repository-tagged

      - task: publish-docs
        file: fauna-jvm-repository/concourse/tasks/publish-docs.yml
        params:
          GIT_PRIVATE_KEY: ((github-ssh-key))

      - put: fauna-jvm-repository-docs
        params:
          repository: fauna-jvm-repository-updated-docs
