---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook))

  - name: fauna-jvm-repository
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/fauna-jvm.git
      branch: main
      private_key: ((github-ssh-key))

  - name: fauna-jvm-repository-docs
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/fauna-jvm.git
      branch: gh-pages
      private_key: ((github-ssh-key))

jobs:
  - name: set-self
    serial: true
    plan:
      - get: fauna-jvm-repository
        trigger: true
      - get: fauna-jvm-repository-docs
        trigger: true
      - set_pipeline: self
        file: fauna-jvm-repository/concourse/pipeline.yml
  - name: release
    serial: true
    public: false
    plan:
      - get: fauna-jvm-repository
        passed: [set-self]
      - get: fauna-jvm-repository-docs
        passed: [set-self]

      # - in_parallel:
      #   - task: integration-tests-oracle-jdk11
      #     file: fauna-jvm-repository/concourse/tasks/integration-tests-oracle-jdk11.yml
      #     privileged: true
      #     vars:
      #       aws_access_key_id: ((concourse_aws_access_key_id))
      #       aws_secret_access_key: ((concourse_aws_access_key_secret))
      #     params:
      #       FAUNA_ROOT_KEY: ((fauna.secret))
      #       FAUNA_DOMAIN: ((fauna.domain))
      #       FAUNA_SCHEME: ((fauna.scheme))
      #       FAUNA_PORT: ((fauna.port))
      #       AWS_ACCESS_KEY_ID: ((concourse_aws_access_key_id))
      #       AWS_SECRET_ACCESS_KEY: ((concourse_aws_access_key_secret))
      #       AWS_DEFAULT_REGION: us-east-2

      #   - task: integration-tests-openjdk11
      #     file: fauna-jvm-repository/concourse/tasks/integration-tests-jdk11.yml
      #     privileged: true
      #     params:
      #       FAUNA_ROOT_KEY: ((fauna.secret))
      #       FAUNA_DOMAIN: ((fauna.domain))
      #       FAUNA_SCHEME: ((fauna.scheme))
      #       FAUNA_PORT: ((fauna.port))

      - task: publish
        file: fauna-jvm-repository/concourse/tasks/publish.yml
        params:
          MAVENCENTRAL_USER: ((mavencentral-user))
          MAVENCENTRAL_PASSWORD: ((mavencentral-password))
          SIGNING_KEYID: ((gpg-keyid))
          SIGNING_KEY: ((gpg-private-key))
          SIGNING_KEYPASSWORD: ((gpg-passphrase))
        on_success:
          put: notify
          params:
            text_file: slack-message/publish

      - task: publish-docs
        file: fauna-jvm-repository/concourse/tasks/publish-docs.yml

      - put: fauna-jvm-repository-docs
        params:
          repository: fauna-jvm-repository-updated-docs
