name: Run Gradle Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      fauna:
        image: fauna/faunadb
        ports:
          - 8443:8443

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: corretto

    - name: Run checkstyle
      run: ./gradlew checkstyleMain

    - name: Run Gradle test
      run: ./gradlew test -i

    - name: Run Gradle javadoc
      run: ./gradlew javadoc

    - name: Run Gradle assemble
      run: ./gradlew assemble
